// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzknqhvjokfeaiymrrdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6a25xaHZqb2tmZWFpeW1ycmRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxMzUwOTgsImV4cCI6MjA1NTcxMTA5OH0.FTl6rOujVfpGQ_3JYh-hgaQVUDPp1mG6VfwpGdFvPMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);